// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Subsystems/WorldSubsystem.h"
#include "BotanicusEnvironmentSubsystem.generated.h"

/**
 * Single query point for the climate at a world position. It currently
 * resolves the seasonal baseline, greenhouse membership, climate equipment
 * and the gentle microclimate generated by nearby living plants.
 */
UCLASS()
class BOTANICUS_API UBotanicusEnvironmentSubsystem : public UWorldSubsystem
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintPure, Category="Botanicus|Environment")
	bool GetEnvironmentAtLocation(
		const FVector& WorldLocation,
		float& OutTemperatureCelsius,
		float& OutAirHumidityPercent,
		float& OutLuminosityPercent,
		bool& bOutInsideGreenhouse) const;
};
