// Copyright Epic Games, Inc. All Rights Reserved.
#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "Growing/BotanicusPlantCatalog.h"
#include "BotanicusBotanistNotebookWidget.generated.h"

class ABotanicusPlayerController;
class UButton;
class UImage;
class UTextBlock;

/** Designer-authored, two-page botanist notebook opened with I. */
UCLASS()
class BOTANICUS_API UBotanicusBotanistNotebookWidget : public UUserWidget
{
	GENERATED_BODY()

public:
	void InitializeWithController(ABotanicusPlayerController* InController);
	void RefreshNotebook();

protected:
	virtual void NativeOnInitialized() override;
	virtual FReply NativeOnKeyDown(
		const FGeometry& InGeometry,
		const FKeyEvent& InKeyEvent) override;

private:
	struct FPlantPageWidgets
	{
		TWeakObjectPtr<UTextBlock> Name;
		TWeakObjectPtr<UTextBlock> Illustration;
		TWeakObjectPtr<UImage> IllustrationImage;
		TWeakObjectPtr<UImage> ElementIcon;
		TWeakObjectPtr<UImage> TemperatureIcon;
		TWeakObjectPtr<UImage> AirHumidityIcon;
		TWeakObjectPtr<UImage> LuminosityIcon;
		TWeakObjectPtr<UImage> WaterIcon;
		TWeakObjectPtr<UImage> GrowthIcon;
		TWeakObjectPtr<UTextBlock> Element;
		TWeakObjectPtr<UTextBlock> Temperature;
		TWeakObjectPtr<UTextBlock> AirHumidity;
		TWeakObjectPtr<UTextBlock> Luminosity;
		TWeakObjectPtr<UTextBlock> Water;
		TWeakObjectPtr<UTextBlock> Growth;
		TWeakObjectPtr<UTextBlock> Note;
	};

	void BindDesignerWidgets();
	void BindPageWidgets(const TCHAR* Prefix, FPlantPageWidgets& OutWidgets);
	void DiscoverPlantsInWorld();
	void RebuildFilteredPlantIndices();
	void ApplyLetterFilter(TCHAR Letter);
	void ApplyElementFilter(EBotanicusPlantElement Element);
	void UpdateTabVisuals();
	void RefreshCurrentSpread();
	void ShowPlantOnPage(const FPlantPageWidgets& Page, int32 PlantIndex) const;
	void JumpToLetter(TCHAR Letter);
	void SetDetailText(
		const TWeakObjectPtr<UTextBlock>& Label,
		const FText& Text) const;
	FText BuildPlantNote(const FBotanicusPlantDefinition& Definition) const;

	UFUNCTION() void HandlePreviousPageClicked();
	UFUNCTION() void HandleNextPageClicked();
	UFUNCTION() void HandleCloseClicked();
	UFUNCTION() void HandleElementAllClicked();
	UFUNCTION() void HandleElementNormalClicked();
	UFUNCTION() void HandleElementFireClicked();
	UFUNCTION() void HandleElementWaterClicked();
	UFUNCTION() void HandleElementShadowClicked();
	UFUNCTION() void HandleElementIceClicked();

	// Keep these declarations explicit: UnrealHeaderTool does not discover
	// UFUNCTION declarations generated by a preprocessor macro.
	UFUNCTION() void HandleLetterAClicked();
	UFUNCTION() void HandleLetterBClicked();
	UFUNCTION() void HandleLetterCClicked();
	UFUNCTION() void HandleLetterDClicked();
	UFUNCTION() void HandleLetterEClicked();
	UFUNCTION() void HandleLetterFClicked();
	UFUNCTION() void HandleLetterGClicked();
	UFUNCTION() void HandleLetterHClicked();
	UFUNCTION() void HandleLetterIClicked();
	UFUNCTION() void HandleLetterJClicked();
	UFUNCTION() void HandleLetterKClicked();
	UFUNCTION() void HandleLetterLClicked();
	UFUNCTION() void HandleLetterMClicked();
	UFUNCTION() void HandleLetterNClicked();
	UFUNCTION() void HandleLetterOClicked();
	UFUNCTION() void HandleLetterPClicked();
	UFUNCTION() void HandleLetterQClicked();
	UFUNCTION() void HandleLetterRClicked();
	UFUNCTION() void HandleLetterSClicked();
	UFUNCTION() void HandleLetterTClicked();
	UFUNCTION() void HandleLetterUClicked();
	UFUNCTION() void HandleLetterVClicked();
	UFUNCTION() void HandleLetterWClicked();
	UFUNCTION() void HandleLetterXClicked();
	UFUNCTION() void HandleLetterYClicked();
	UFUNCTION() void HandleLetterZClicked();

	UPROPERTY(Transient)
	TObjectPtr<ABotanicusPlayerController> BotanicusController;
	UPROPERTY(Transient)
	TObjectPtr<UButton> CloseButtonWidget;
	UPROPERTY(Transient)
	TObjectPtr<UButton> PreviousPageButtonWidget;
	UPROPERTY(Transient)
	TObjectPtr<UButton> NextPageButtonWidget;

	FPlantPageWidgets LeftPageWidgets;
	FPlantPageWidgets RightPageWidgets;
	TArray<TWeakObjectPtr<UButton>> AlphabetButtons;
	TArray<TWeakObjectPtr<UButton>> ElementButtons;

	UPROPERTY(Transient)
	TArray<FBotanicusPlantDefinition> PlantDefinitions;
	TArray<int32> FilteredPlantIndices;
	TSet<FName> DiscoveredPlantKeys;
	TCHAR ActiveLetterFilter = 0;
	TOptional<EBotanicusPlantElement> ActiveElementFilter;
	int32 CurrentPageStartIndex = 0;
};
